alter table "public"."Historial_Fuentes" alter column "HFuente_ID" drop default;

alter table "public"."Historial_Fuentes" alter column "HFuente_ID" add generated by default as identity;

alter table "public"."Historial_Fuentes" alter column "HFuente_ID" set data type integer using "HFuente_ID"::integer;

alter table "public"."Historial_Recompensas" alter column "HRecompensa_ID" drop default;

alter table "public"."Historial_Recompensas" alter column "HRecompensa_ID" add generated by default as identity;

alter table "public"."Historial_Recompensas" alter column "HRecompensa_ID" set data type integer using "HRecompensa_ID"::integer;

alter table "public"."Historial_Temas" alter column "HTema_ID" drop default;

alter table "public"."Historial_Temas" alter column "HTema_ID" add generated by default as identity;

alter table "public"."Historial_Temas" alter column "HTema_ID" set data type integer using "HTema_ID"::integer;
