alter table "public"."Insignia_Conseguida" drop constraint "Insignia_Conseguida_pkey";

alter table "public"."Miembro_Proyecto" drop constraint "Miembro_Proyecto_pkey";

drop index if exists "public"."Insignia_Conseguida_pkey";

drop index if exists "public"."Miembro_Proyecto_pkey";

alter table "public"."Insignia_Conseguida" add column "Insignia_Conseguida_ID" integer generated by default as identity not null;

alter table "public"."Miembro_Proyecto" add column "Miembro_ID" integer generated by default as identity not null;

CREATE UNIQUE INDEX "Insignia_Conseguida_Insignia_Conseguida_ID_key" ON public."Insignia_Conseguida" USING btree ("Insignia_Conseguida_ID");

CREATE UNIQUE INDEX "Miembro_Proyecto_Miembro_ID_key" ON public."Miembro_Proyecto" USING btree ("Miembro_ID");

CREATE UNIQUE INDEX "UNIQUE_Usuario_Insignia" ON public."Insignia_Conseguida" USING btree ("Usuario_ID", "Insignia_ID");

CREATE UNIQUE INDEX "UNIQUE_Usuario_Proyecto" ON public."Miembro_Proyecto" USING btree ("Usuario_ID", "Proyecto_ID");

CREATE UNIQUE INDEX "Insignia_Conseguida_pkey" ON public."Insignia_Conseguida" USING btree ("Insignia_Conseguida_ID");

CREATE UNIQUE INDEX "Miembro_Proyecto_pkey" ON public."Miembro_Proyecto" USING btree ("Miembro_ID");

alter table "public"."Insignia_Conseguida" add constraint "Insignia_Conseguida_pkey" PRIMARY KEY using index "Insignia_Conseguida_pkey";

alter table "public"."Miembro_Proyecto" add constraint "Miembro_Proyecto_pkey" PRIMARY KEY using index "Miembro_Proyecto_pkey";

alter table "public"."Insignia_Conseguida" add constraint "Insignia_Conseguida_Insignia_Conseguida_ID_key" UNIQUE using index "Insignia_Conseguida_Insignia_Conseguida_ID_key";

alter table "public"."Miembro_Proyecto" add constraint "Miembro_Proyecto_Miembro_ID_key" UNIQUE using index "Miembro_Proyecto_Miembro_ID_key";

